spring.application.name=back-end

# -------------------------
# Database Configuration
# -------------------------
spring.datasource.url=jdbc:mysql://172.21.133.36/cms?usessl=false
spring.datasource.username=root
spring.datasource.password=C2u8cthHaHuokmK5h91prpBB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:tfylcTDZ1cjCwFVMqa6LLWMh@172.21.97.86:27017/prescriptions?authSource=admin"

management.endpoint.health.show-details=always
management.health.db.enabled=true

api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M

# -------------------------
# Static Resources
# -------------------------
# Serve static files from src/main/resources/static/
spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
# Location of Thymeleaf templates
spring.thymeleaf.prefix=classpath:/templates/

# All templates end with .html
spring.thymeleaf.suffix=.html

# Render mode (HTML5)
spring.thymeleaf.mode=HTML

# Disable caching during development
spring.thymeleaf.cache=false

# UTF-8 encoding for all templates
spring.thymeleaf.encoding=UTF-8

